1)Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.

a. Use a numpy function to make all elements uppercase.

b. Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

c. Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.


2) Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 45.

a. Use numpy to find the sum and the product of the elements of this array.

b. Use numpy to take the natural log of each element.

c. Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array.

In [2]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

1)Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.


In [3]:
mearray = np.array(['Matt', 'Doudnikoff', 'North Carolina', 'Blue'])

In [4]:
mearray

array(['Matt', 'Doudnikoff', 'North Carolina', 'Blue'], dtype='<U14')

a. Use a numpy function to make all elements uppercase.

In [5]:
uppercase = np.char.upper(mearray)
uppercase

array(['MATT', 'DOUDNIKOFF', 'NORTH CAROLINA', 'BLUE'], dtype='<U14')

b. Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

In [6]:
count = np.char.count(mearray, 'a')
count

array([1, 0, 2, 0])

c. Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.

In [7]:
mylen = np.vectorize(len)
print(mylen(mearray))

[ 4 10 14  4]


2) Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 45.

In [8]:
numbers = np.arange(1,46,4)
numbers

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

a. Use numpy to find the sum and the product of the elements of this array.

In [9]:
sumnum = np.sum(numbers)
sumnum

276

In [10]:
np.prod(numbers)

616159193

b. Use numpy to take the natural log of each element.

In [11]:
logarray = np.log(numbers)
logarray

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

c. Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array.

In [12]:
numbers1 = np.delete(numbers,0)
numbers2 = np.delete(numbers,-1)

In [13]:
numbers1 + numbers2

array([ 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86])